#pragma once

#include "util/logger/Logger.hpp"

DECLARE_LOGGER(APPLICATION, trace);
DECLARE_LOGGER(APPLICATION_INITIALIZATION, trace);
DECLARE_LOGGER(VULKAN, trace);

DECLARE_LOGGER_GROUP(
    QUARTZ,
    3,
    APPLICATION,
    APPLICATION_INITIALIZATION,
    VULKAN
);
