#pragma once

#include "util/logger/Logger.hpp"

DECLARE_LOGGER(APPLICATION, trace);
DECLARE_LOGGER(APPLICATION_INITIALIZATION, trace);

DECLARE_LOGGER_GROUP(
    QUARTZ,
    2,
    APPLICATION,
    APPLICATION_INITIALIZATION
);
