#pragma once

#include "util/logger/Logger.hpp"

DECLARE_LOGGER(COLLIDER, trace);
DECLARE_LOGGER(COLLIDER_BOX, trace);
DECLARE_LOGGER(COLLIDER_SPHERE, trace);
DECLARE_LOGGER(RIGIDBODY, trace);

DECLARE_LOGGER_GROUP(
    QUARTZ_PHYSICS,
    4,
    COLLIDER,
    COLLIDER_BOX,
    COLLIDER_SPHERE,
    RIGIDBODY
);