#pragma once

#include "util/logger/Logger.hpp"

DECLARE_LOGGER(COLLIDER, trace);
DECLARE_LOGGER(SHAPE_BOX, trace);
DECLARE_LOGGER(SHAPE_SPHERE, trace);
DECLARE_LOGGER(FIELD, trace);
DECLARE_LOGGER(RIGIDBODY, trace);

DECLARE_LOGGER_GROUP(
    QUARTZ_PHYSICS,
    5,
    COLLIDER,
    SHAPE_BOX,
    SHAPE_SPHERE,
    FIELD,
    RIGIDBODY
);

