#pragma once

#include "util/logger/Logger.hpp"

DECLARE_LOGGER(BUFFER, trace);
DECLARE_LOGGER(CONTEXT, trace);
DECLARE_LOGGER(DEPTHBUFFER, trace);
DECLARE_LOGGER(DEVICE, trace);
DECLARE_LOGGER(INSTANCE, trace);
DECLARE_LOGGER(MATERIAL, trace);
DECLARE_LOGGER(MESH, trace);
DECLARE_LOGGER(MODEL, trace);
DECLARE_LOGGER(MODEL_NODE, trace);
DECLARE_LOGGER(MODEL_SCENE, trace);
DECLARE_LOGGER(PIPELINE, trace);
DECLARE_LOGGER(SWAPCHAIN, trace);
DECLARE_LOGGER(TEXTURE, trace);
DECLARE_LOGGER(VULKAN, trace);
DECLARE_LOGGER(VULKANUTIL, trace);
DECLARE_LOGGER(WINDOW, trace);

DECLARE_LOGGER_GROUP(
        QUARTZ_RENDERING,
        16,
        BUFFER,
        CONTEXT,
        DEPTHBUFFER,
        DEVICE,
        INSTANCE,
        MATERIAL,
        MESH,
        MODEL,
        MODEL_NODE,
        MODEL_SCENE,
        PIPELINE,
        SWAPCHAIN,
        TEXTURE,
        VULKAN,
        VULKANUTIL,
        WINDOW
);
