name: Quartz Linux Unit Tests

on:
  push:
    branches:
      - "kjk/ci_ssh"

jobs:
  ssh-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Validate sshpass exists
        run: sshpass -h
      - name: SSH With Password
        run: sshpass -p "${{ secrets.JADE_RUNNER_PASSWORD }}" "${{ secrets.JADE_RUNNER_USERNAME }}"@"${{ secrets.JADE_IP }}"
      - name: SSH Set up
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/private_key
          echo "$PRIVATE_KEY" >> ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          cat >>~/.ssh/config <<END
          Host jade-runner
            HostName $JADE_IP
            User $JADE_USER
            IdentityFile ~/.ssh/private_key
            StrictHostKeyChecking no
          END
        env:
          JADE_USER: ${{ secrets.JADE_RUNNER_USERNAME }}
          JADE_IP: ${{ secrets.JADE_IP }}
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: SSH In
        run: ssh jade-runner 'whoami ; pwd ; echo hello world'

      - name: Get SSH Keys
        run: |
          echo "working directory:"
          pwd
          echo " "
          echo "user:"
          whoami
          echo " "
          echo "make ssh directory"
          mkdir ~/.ssh
          echo " "
          echo "home directory contents:"
          ls -lash ~
          echo " "
          echo "create private key file"
          touch ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo " "
          echo "populate private key with secret"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo " "
          echo "create known hosts file"
          touch ~/.ssh/known_hosts
          echo " "
          echo "populate known hosts"
          echo "${{ secrets.JADE_HOST_SIGNATURES }}" >> ~/.ssh/known_hosts
      - name: SSH Into Jade
        run: |
          echo "working directory:"
          pwd
          echo " "
          echo "user:"
          whoami
          echo " "
          echo "home directory contents:"
          ls -lash ~
          echo " "
          echo "starting ssh agent"
          eval $(ssh-agent -s)
          echo " "
          echo "adding private key to ssh agent"
          ssh-add ~/.ssh/id_rsa
          echo " "
          echo "working directory:"
          pwd
          echo " "
          echo "ssh directory contents:"
          ls -lash ~/.ssh
          echo " "
          echo "sshing into jade"
          ssh -t -t "${{ secrets.JADE_RUNNER_USERNAME }}"@"${{ secrets.JADE_IP }}"
          echo " "
          echo "working directory:"
          pwd
          echo " "
          echo "user:"
          whoami
      - name: Hello world
        run: echo "Hello world"

