name: Quartz Linux Unit Tests

on:
  # pull_request:
  #   branches:
  #     - "master"
  push:
    branches:
      - "kjk/ci"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Do it all
        run: mkdir .debug ; cd .debug ; cmake .. -DCMAKE_BUILD_TYPE=Debug -DQUARTZ_COMPILE_UNIT_TESTS=True -DGLFW_BUILD_WAYLAND=OFF -DGLFW_BUILD_X11=ON ; ninja ; ctest

