name: Quartz Linux Unit Tests

on:
  push:
    branches:
      - "kjk/ci_ssh"

jobs:
  ssh-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # ===========================================================================================
      # This is the variant which attempts to use ssh to get into jade for building and running
      # tests there
      #
      # This is not working because jade is not configured to accept ssh sessions from outside of
      # the local network
      # ===========================================================================================
      - name: Validate sshpass exists
        run: sshpass -h
      - name: Setup ~/.ssh directory
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
      - name: Populate known hosts file
        run: echo "${{ secrets.JADE_HOST_SIGNATURES }}" >> ~/.ssh/known_hosts
      - name: SSH With Password
        run: sshpass -e ssh -vvv -tt ${{ secrets.JADE_RUNNER_USERNAME }}@${{ secrets.JADE_IP }} "whoami ; pwd"
        env:
          SSHPASS: ${{ secrets.JADE_RUNNER_PASSWORD }}

