name: Quartz Linux Unit Tests

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Hello world
        run: echo "Hello world"

