name: Quartz Linux Unit Tests

on:
  push:
    branches:
      - "kjk/ci_ssh"

jobs:
  ssh-build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Validate sshpass exists
        run: sshpass -h
      - name: Setup ~/.ssh directory
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
      - name: Populate known hosts file
        run: echo "${{ secrets.JADE_HOST_SIGNATURES }}" >> ~/.ssh/known_hosts
      - name: SSH With Password
        run: sshpass -e ssh -vv -tt ${{ secrets.JADE_RUNNER_USERNAME }}@${{ secrets.JADE_IP }} "whoami ; pwd"
        env:
          SSHPASS: ${{ secrets.JADE_RUNNER_PASSWORD }}
      - name: Hello world
        run: echo "Hello world"

