name: Quartz Linux Unit Tests

on:
  push:
    branches:
      - "kjk/ci_ssh"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get SSH Keys
        run: |
          echo "pwd"
          pwd
          echo ""
          echo "whoami"
          whoami
          echo ""
          echo "mkdir ~/.ssh"
          mkdir ~/.ssh
          echo ""
          echo "ls lash ~"
          ls ~
          echo ""
          echo "touch ~/.ssh/id_rsa"
          touch ~/.ssh/id_rsa
          echo ""
          echo "populate private key with secret"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo ""
          echo "ping google"
          ping google.com
          echo ""
          echo "keyscan google"
          ssh-keyscan google.com
          echo ""
          echo "populate known hosts"
          ssh-keyscan -H "${{ secrets.JADE_IP }}" >> ~/.ssh/known_hosts
      - name: SSH Into Jade
        run: |
          pwd
          whoami
          ls ~
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          pwd
          ls ~/.ssh
          cat ~/.ssh/known_hosts
          ssh "${{ secrets.JADE_RUNNER_USERNAME }}"."${{ secrets.JADE_IP }}"
          pwd
      - name: Hello world
        run: echo "Hello world"

